/* Generated by scripts/art-sizes.mjs. Do not edit by hand. */

/**
 * How big each picture in the archive actually is, by the path a record
 * points at. Read `scripts/art-sizes.mjs` for why this exists; read
 * `LEAD_MIN_WIDTH` in `archive-items.ts` for what it is used for.
 */
export const artSizes: Record<string, readonly [number, number]> = {
  '/images/articles/anatomy-of-a-blessing.jpg': [1024, 683],
  '/images/articles/bread-in-the-wilderness.jpg': [960, 640],
  '/images/articles/creeds-still-speak.jpg': [1024, 729],
  '/images/articles/discipline-of-waiting.jpg': [1024, 683],
  '/images/articles/dress-code-headscarves.jpg': [1635, 962],
  '/images/articles/dress-code-portrait.jpg': [526, 701],
  '/images/articles/holiness-puzzle.webp': [992, 558],
  '/images/articles/hope-is-a-discipline.jpg': [1024, 678],
  '/images/articles/importance-of-repentance-wide.webp': [485, 303],
  '/images/articles/importance-of-repentance.webp': [1288, 767],
  '/images/articles/praying-the-hours.jpg': [960, 640],
  '/images/articles/prophetic-timeline-wide.webp': [1468, 918],
  '/images/articles/prophetic-timeline.webp': [1516, 998],
  '/images/articles/rapture-of-the-church-wide.webp': [648, 406],
  '/images/articles/rapture-of-the-church.webp': [1024, 1536],
  '/images/articles/repentance-and-holiness-wide.webp': [1228, 768],
  '/images/articles/repentance-and-holiness.webp': [1376, 768],
  '/images/articles/requirements-to-enter-heaven-wide.webp': [1008, 630],
  '/images/articles/requirements-to-enter-heaven.webp': [1200, 630],
  '/images/articles/shepherds-and-platforms.jpg': [1600, 1067],
  '/images/articles/testimony-nairobi-nights.jpg': [1024, 683],
  '/images/articles/unforgivable-sin-wide.webp': [648, 406],
  '/images/articles/unforgivable-sin.webp': [1024, 1536],
  '/images/articles/watchmen-not-alarmists.jpg': [1024, 676],
  '/images/articles/wells-our-fathers-dug.jpg': [1600, 900],
  '/images/articles/why-jesus-died-on-the-cross-wide.webp': [896, 560],
  '/images/articles/why-jesus-died-on-the-cross.webp': [1536, 1024],
}
