/**
 * The intrinsic size of every picture in `public/images/articles`,
 * written into `src/lib/art-sizes.ts`.
 *
 * The listing needs this for one decision it cannot make from a path: a
 * picture is only allowed to run as the front page's lead if the file is
 * actually big enough to be one. Most of this archive's landscape crops
 * are the wordless region of a poster, and that region is as wide as it
 * is — `importance-of-repentance-wide.webp` stops at 485px because the
 * next column of pixels is the gold headline. Run at lead size a file
 * like that is upscaled, and an upscaled photograph at the top of the
 * page is worse than no lead at all.
 *
 * Generated rather than hand-kept, because a hand-kept table of numbers
 * about files is a table that goes wrong the first time somebody re-cuts
 * a crop. `tests/lead-piece.test.ts` regenerates it and fails if what is
 * committed no longer matches the files.
 *
 *   node scripts/art-sizes.mjs           write it
 *   node scripts/art-sizes.mjs --check   exit 1 if stale
 */
import { createRequire } from 'node:module'
import fs from 'node:fs/promises'
import path from 'node:path'

const require = createRequire(import.meta.url)
const sharp = require('sharp')

const DIR = path.join(process.cwd(), 'public', 'images', 'articles')
const OUT = path.join(process.cwd(), 'src', 'lib', 'art-sizes.ts')

export async function render() {
  const files = (await fs.readdir(DIR)).filter((f) => /\.(webp|jpe?g|png|avif)$/i.test(f)).sort()
  const rows = []
  for (const file of files) {
    const { width, height } = await sharp(path.join(DIR, file)).metadata()
    if (width && height) rows.push(`  '/images/articles/${file}': [${width}, ${height}],`)
  }
  return `/* Generated by scripts/art-sizes.mjs. Do not edit by hand. */

/**
 * How big each picture in the archive actually is, by the path a record
 * points at. Read \`scripts/art-sizes.mjs\` for why this exists; read
 * \`LEAD_MIN_WIDTH\` in \`archive-items.ts\` for what it is used for.
 */
export const artSizes: Record<string, readonly [number, number]> = {
${rows.join('\n')}
}
`
}

const source = await render()
if (process.argv.includes('--check')) {
  const held = await fs.readFile(OUT, 'utf8').catch(() => '')
  if (held !== source) {
    console.error('src/lib/art-sizes.ts is stale — run: node scripts/art-sizes.mjs')
    process.exit(1)
  }
  console.log('art-sizes.ts is current')
} else {
  await fs.writeFile(OUT, source)
  console.log(`wrote ${OUT}`)
}
